# GENERATED BY CHAT GPT
using GLMakie
using CairoMakie

GLMakie.activate!()

# Generate dummy code phase and Doppler axes
code_phase = 0:500:16000
doppler = -5000:500:5000

# Create a grid
Z = zeros(length(code_phase), length(doppler))

# Simulate a correlation peak at a given Doppler and code phase
peak_phase_idx = findall(x -> x == 8000, code_phase)[1]
peak_doppler_idx = findall(x -> x == 2000, doppler)[1]

# Fill with noise and one peak
for i in 1:length(code_phase)
    for j in 1:length(doppler)
        Z[i, j] = rand() * 50  # background noise
    end
end

# Add correlation peak (e.g., GNSS signal detection)
Z[peak_phase_idx, peak_doppler_idx] += 500

# Plot
f = Figure(size=(600, 600), fonts = (; regular = "Times New Roman", bold = "Times New Roman", bold_italic = "Times New Roman", italic = "Times New Roman"))
ax = Axis3(f[1, 1]; 
    xlabel = "Code Offset [samples]", ylabel = "Doppler Shift [Hz]", zlabel = "Correlation",    
    viewmode = :fit, limits =(code_phase[1], code_phase[end], doppler[1], doppler[end], 0, 0.7),
    xticks = [0:4000:16000...], yticks = [-5000:3000:5000...], zticks = [0:0.1:0.7...],)
surface!(ax, code_phase, doppler, Z/1000)
save("results/sigacquisitionplot.pdf", f, size = (600, 400), backend = CairoMakie, update = false)
f